### ISSUE TITLE
Error "invalid_grant" on specific environment

### ISSUE THREAD

**Issue by GerkinDev** [jsguy/ga-api#3]
Hi,
I'm trying to use your module to retrieve stats infos from Google Analytics. On dev & test servers, everything works well. But on production, I have the following error:

```
Error: invalid_grant
    at Request._callback (/appdir/node_modules/gtoken/lib/index.js:215:34)
    at Request.self.callback (/appdir/node_modules/gtoken/node_modules/request/request.js:187:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/appdir/node_modules/gtoken/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:107:17)
    at IncomingMessage.<anonymous> (/appdir/node_modules/gtoken/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickDomainCallback (node.js:381:11) [Error: invalid_grant]
```

I can't find what is the exact problem. It works on 2 environments, so it may not be a problem with the Google API configuration.... Can you please help me?

Cheers

**Comment by jsguy** [comment]
I haven't seen that issue myself, but just read in interesting article about it here:

https://medium.com/timekit/google-oauth-invalid-grant-nightmare-and-how-to-fix-it-9f4efaf1da35#.efev5kfhm

Let me know if any of those help/fix the issue.

**Comment by Nihilivin** [comment]
Awesome! The time on the prod server was wrong, I am currently fixing it

**Comment by Wayne-Ehr-Surprenant** [comment]
@Nihilivin 

Is the problem solved now ? How did you fix the time on the server ?

**Comment by jsguy** [comment]
Closing old issue
